version: '3.8'

services:
  web:
    ports:
    - "5000:5000"
    container_name: ots-routing
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: flask run --host=0.0.0.0
    volumes:
      - ./src:/app
    image: ots/ots-routing:latest
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development